config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root   'tasks#index'

  get    '/terms_of_service', to: 'pages#terms_of_service'

  get    '/signup', to: 'users#new'
  post   '/signup', to: 'users#create'
  get    '/thanks', to: 'users#thanks'
  get    '/user_profile', to: 'users#edit'

  get    '/resend_activation', to: 'account_activations#resend'
  get    '/password_resets/confirmation', to: 'password_resets#sent', as: :password_reset_sent

  get    '/login',  to: 'sessions#new'
  post   '/login',  to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get    'settings/edit'
  post   'settings/toggle_display_quotes'

  get    'task_categories/delete_confirmation/:id', to: 'task_categories#delete_confirmation', as: :task_category_delete_with_confirmation

  get    'tasks/upcoming', to: 'tasks#upcoming', as: :upcoming_tasks
  get    'tasks/search', to: 'tasks#search', as: :search_tasks
  post   'task/toggle_task_status/:id', to: 'tasks#toggle_task_status', as: :toggle_task_status
  post   'task/advance_overdue_tasks', to: 'tasks#advance_overdue_tasks', as: :advance_overdue_tasks

  resources :users,               except: [:index, :show, :edit]
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :tasks
  resources :task_categories,     except: [:new]
  resources :quotes,              except: [:new]
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  before_action :get_user,         only: %i[edit update]
  before_action :valid_user,       only: %i[edit update]
  before_action :check_expiration, only: %i[edit update]

  def new
  end

  def create
    email = params[:email].downcase

    @user = User.find_by(email: email)
    if @user
      @user.create_reset_digest
      @user.send_password_reset_email
      flash[:success] =
        'Reset instructions sent to' \
        " #{ActionController::Base.helpers.sanitize(email)}"
      redirect_to password_reset_sent_path
    else
      if email.blank?
        flash.now[:warning] = 'Please enter a valid email address'
      else
        flash.now[:warning] =
          "[#{ActionController::Base.helpers.sanitize(email)}] is not a" \
          ' registered user'
      end
      render 'new'
    end
  end

  def edit
  end

  def update
    if params[:user][:password].empty?
      @user.errors.add(:password, "can't be empty")
      render 'edit'
    elsif @user.update(user_params)
      log_in @user
      @user.update_attribute(:reset_digest, nil)
      flash[:success] = 'Password has been reset'
      redirect_to tasks_path
    else
      render 'edit'
    end
  end

  # This is the page we drop users onto after they've submitted a successful
  # password reset request. This avoids confusion that could arise from
  # redirecting them to the login page or whatnot.
  def sent
  end

  private

  def user_params
    params.require(:user).permit(:password, :password_confirmation)
  end

  # Before filters

  def get_user
    @user = User.find_by(email: params[:email])
  end

  # Confirms a valid user.
  def valid_user
    return if @user&.activated? && @user&.authenticated?(:reset, params[:id])

    flash[:warning] = 'That password reset link was invalid. Please try again.'
    redirect_to new_password_reset_path
  end

  # Checks expiration of reset token.
  def check_expiration
    return unless @user.password_reset_expired?

    @user.password_reset_expired?
    flash[:warning] = 'That password reset link has expired (they expire' \
      ' after 2 hours)'
    redirect_to new_password_reset_path
  end
end

app/views/password_resets/edit.html.erb
<h1>Reset password</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3 mx-auto">
    <%= form_with model: @user, url: password_reset_path(params[:id]), local: true do |f| %>
      <%= hidden_field_tag :email, @user.email %>

      <%= f.label :password, "Password:" %>
      <%= f.password_field :password, placeholder: "Password", class: "form-control #{form_validity_class(@user, 'password')}" %>
      <%= raw validation_error_html(@user, 'password', 'Password') %>

      <%= f.label :password_confirmation, "Confirm Password:" %>
      <%= f.password_field :password_confirmation, placeholder: "Password Confirmation", class: "form-control #{form_validity_class(@user, 'password')}" %>
      <%= raw validation_error_html(@user, 'password_confirmation', 'Password confirmation') %>

      <%= f.submit "Update password", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/password_resets/new.html.erb
<h1>Can't Log In?</h1>

<%= render 'layouts/flash_alerts_static' %>

<div class="container">
  <div class="col-md-6 col-md-offset-3 mx-auto">
    <%= form_with url: password_resets_path, local: true do |f| %>
      <%= f.label :email, "Email Address:" %>
      <%= f.email_field :email, placeholder: "Email", class: 'form-control' %>
      <%= f.submit "Send me password reset instructions", class: "btn btn-primary" %>
    <% end %>

    <small>Or you can just <%= link_to "return to the login page", login_path %></small>
  </div>
</div>

app/views/password_resets/sent.html.erb
<h1>Password Reset Confirmation</h1>

<%= render 'layouts/flash_alerts_static' %>

<div class="container">
  <p>We just sent a special one-time login link to your email address. Please check your mail and click on the link, which will take you to a page where you can set your new password. For security reasons, the login link will expire after two hours.</p>

  <p><strong>Note:</strong> If you don't receive our email after a few minutes, check your Spam/Junk mail folder.</p>
</div>