config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root   'tasks#index'

  get    '/terms_of_service', to: 'pages#terms_of_service'

  get    '/signup', to: 'users#new'
  post   '/signup', to: 'users#create'
  get    '/thanks', to: 'users#thanks'
  get    '/user_profile', to: 'users#edit'

  get    '/resend_activation', to: 'account_activations#resend'
  get    '/password_resets/confirmation', to: 'password_resets#sent', as: :password_reset_sent

  get    '/login',  to: 'sessions#new'
  post   '/login',  to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get    'settings/edit'
  post   'settings/toggle_display_quotes'

  get    'task_categories/delete_confirmation/:id', to: 'task_categories#delete_confirmation', as: :task_category_delete_with_confirmation

  get    'tasks/upcoming', to: 'tasks#upcoming', as: :upcoming_tasks
  get    'tasks/search', to: 'tasks#search', as: :search_tasks
  post   'task/toggle_task_status/:id', to: 'tasks#toggle_task_status', as: :toggle_task_status
  post   'task/advance_overdue_tasks', to: 'tasks#advance_overdue_tasks', as: :advance_overdue_tasks

  resources :users,               except: [:index, :show, :edit]
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :tasks
  resources :task_categories,     except: [:new]
  resources :quotes,              except: [:new]
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :task_category
  belongs_to :user

  # Validation
  STATUS_TYPES = %w[INCOMPLETE COMPLETED].freeze

  validates_presence_of :user_id

  validates :summary, presence: true,
                      length: { maximum: 150 }

  validates :priority, presence: true,
                       inclusion: { in: 1..3 }

  validates :status, presence: true,
                     inclusion: { in: STATUS_TYPES }

  # Scopes
  scope :incomplete,  -> { where(status: :INCOMPLETE) }
  scope :completed,   -> { where(status: :COMPLETED) }
  scope :no_due_date, -> { where('due_at IS NULL') }

  def self.category(tc_id)
    where(task_category_id: tc_id)
  end

  # Reassign a task collection to a different Task Category
  def self.move_to_category(tc_id)
    update_all(task_category_id: tc_id)
  end

  # today_db should be today's date in database format (yyyy-mm-dd). It's
  # passed as an argument to allow its caller to apply the user's time
  # zone to the date.
  #
  # Current tasks are due today or before, or have no due date set
  def self.current(today_db)
    incomplete.where('due_at <= ?', today_db)
              .order(due_at: :asc, priority: :asc) +
      incomplete.no_due_date.order(priority: :asc)
  end

  # today_db should be today's date in database format (yyyy-mm-dd). It's
  # passed as an argument to allow its caller to apply the user's time
  # zone to the date.
  def self.current_with_due_dates(today_db)
    incomplete.where('due_at <= ?', today_db)
              .order(due_at: :asc, priority: :asc)
  end

  # Boolean method that returns whether the task is "current", i.e. would be
  # displayed in the Current Tasks tab (instead of Upcoming Tasks). today_db
  # should be today's date in database format (yyyy-mm-dd). It's passed as an
  # argument to allow its caller to apply the user's time zone to the date.
  def current?(today_db)
    due_at.to_s <= today_db || due_at.nil?
  end

  # Boolean method that returns whether the task is "upcoming", i.e. would be
  # displayed in the Upcoming Tasks tab (instead of Current Tasks). today_db
  # should be today's date in database format (yyyy-mm-dd). It's passed as an
  # argument to allow its caller to apply the user's time zone to the date.
  def upcoming?(today_db)
    due_at.to_s > today_db
  end

  # today_db should be today's date in database format (yyyy-mm-dd). It's
  # passed as an arguent to allow its caller to apply the user's time
  # zone to the date.
  def self.overdue(today_db)
    incomplete.where('due_at < ?', today_db).order(due_at: :asc, priority: :asc)
  end

  # today_db should be today's date in database format (yyyy-mm-dd). It's
  # passed as an argument to allow its caller to apply the user's time
  # zone to the date.
  def self.future(today_db)
    incomplete.where('due_at > ?', today_db).order(due_at: :asc, priority: :asc)
  end

  # today_start_db and today_end_db should be DateTimes of the start and
  # end of today. They are passed as arguments to allow its caller to
  # apply the user's time zone to the dates.
  def self.completed_today(today_start_db, today_end_db)
    completed.where('completed_at BETWEEN ? AND ?', today_start_db,
                    today_end_db).order(due_at: :asc, priority: :asc)
  end

  def self.search(summary_terms, completed_status, category_id, sort_by)
    tasks = all
    tasks = tasks.where('summary LIKE ?', "%#{summary_terms}%") unless
      summary_terms.empty?
    tasks = tasks.completed if completed_status == 'completed'
    tasks = tasks.incomplete if completed_status == 'incomplete'
    tasks = tasks.category(category_id) if category_id != 'All'

    return tasks.order('due_at asc') if sort_by.nil?

    # customize the sort order
    return tasks.order(due_at: :asc) if sort_by == 'due-date-asc'
    return tasks.order(due_at: :desc) if sort_by == 'due-date-desc'
    return tasks.order(priority: :asc) if sort_by == 'priority-asc'
    return tasks.order(priority: :desc) if sort_by == 'priority-desc'

    # if we've reached this point, something isn't right (a malicious user may
    # be messing with the sort_by string), so to prevent a site crash, just
    # return an empty array
    []
  end

  # Returns a boolean based on the tasks' status: INCOMPLETE as false,
  # COMPLETED as true
  def status_as_boolean
    return false if status == 'INCOMPLETE'
    return true if status == 'COMPLETED'

    false
  end

  def toggle_status
    if status == 'INCOMPLETE'
      update_attribute(:status, 'COMPLETED')
      update_attribute(:completed_at, Time.now)
    else
      update_attribute(:status, 'INCOMPLETE')
      update_attribute(:completed_at, nil)
    end
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :logged_in_user

  def index
    @new_task = Task.new
    tc_filter = params[:category]
    if tc_filter.nil?
      @current_tasks = current_user.tasks.current(today_db)
                                   .paginate(page: params[:page], per_page: 20)
    else
      tc_id = current_user.task_categories.find_by(name: tc_filter)
      @current_tasks = current_user.tasks.category(tc_id).current(today_db)
                                   .paginate(page: params[:page], per_page: 20)
    end

    @completed_tasks = current_user.tasks.completed_today(today_start_db,
                                                          today_end_db)
    @overdue_tasks = current_user.tasks.overdue(today_db).count
    @quote = random_quote
    @awwyiss_modal = random_awwyiss_modal
  end

  def upcoming
    @new_task = Task.new
    tc_filter = params[:category]
    if tc_filter.nil?
      @future_tasks = current_user.tasks.future(today_db)
                                  .paginate(page: params[:page], per_page: 20)
    else
      tc_id = current_user.task_categories.find_by(name: tc_filter)
      @future_tasks = current_user.tasks.category(tc_id).future(today_db)
                                  .paginate(page: params[:page], per_page: 20)
    end
    @quote = random_quote
    @awwyiss_modal = random_awwyiss_modal
  end

  def show
    @task = current_user.tasks.find_by(id: params[:id])
    if @task.nil?
      flash[:danger] = 'Task not found'
      redirect_to_correct_tasks_tab && return
    end

    respond_to do |f|
      f.js
    end
  end

  def new
    @new_task = Task.new
  end

  def create
    @new_task = current_user.tasks.build(task_params)
    if @new_task.save
      flash[:success] = task_change_flash_msg(@new_task, params[:tasks_view],
                                              'New task created')
      redirect_to_correct_tasks_tab
    else
      @new_task.destroy!
      @current_tasks = current_user.tasks.current(today_db)
                                   .paginate(page: params[:page], per_page: 20)
      @completed_tasks = current_user.tasks
                                     .completed_today(today_start_db,
                                                      today_end_db)
      @future_tasks = current_user.tasks.future(today_db)
                                  .paginate(page: params[:page], per_page: 20)
      @overdue_tasks = current_user.tasks.overdue(today_db).count
      @quote = random_quote
      @awwyiss_modal = random_awwyiss_modal
      render_correct_tasks_tab
    end
  end

  def edit
    @task = current_user.tasks.find_by(id: params[:id])
    if @task.nil?
      flash[:danger] = 'Task not found'
      redirect_to_correct_tasks_tab && return
    end

    respond_to do |f|
      f.js
    end
  end

  def update
    @task = current_user.tasks.find_by(id: params[:id])
    if @task.nil?
      flash[:danger] = 'Updating task failed: task not found'
      redirect_to_correct_tasks_tab && return
    end

    if @task.update(task_params)
      flash[:success] = task_change_flash_msg(@task, params[:tasks_view],
                                              'Task updated')
    end
    redirect_to_correct_tasks_tab
  end

  def destroy
    @task = current_user.tasks.find_by(id: params[:id])
    if @task.nil?
      flash[:danger] = 'Deleting task failed: task not found'
      redirect_to_correct_tasks_tab && return
    end

    @task.destroy
    flash[:success] = 'Task deleted'
    redirect_to_correct_tasks_tab
  end

  def toggle_task_status
    @task = current_user.tasks.find_by(id: params[:id])
    if @task.nil?
      flash[:danger] = 'Changing task status failed: task not found'
      redirect_to(tasks_path) && return
    end

    @task.toggle_status
    @task.reload
    @current_tasks = current_user.tasks.current(today_db)
                                 .paginate(page: params[:page], per_page: 20)
    @completed_tasks = current_user.tasks.completed_today(today_start_db,
                                                          today_end_db)
    @awwyiss_modal = random_awwyiss_modal

    respond_to do |f|
      f.js
    end
  end

  def advance_overdue_tasks
    num_overdue_tasks = current_user.tasks.overdue(today_db).count
    current_user.tasks.current_with_due_dates(today_db).update(due_at: today_db)
    @current_tasks = current_user.tasks.current(today_db)
                                 .paginate(page: params[:page], per_page: 20)
    flash[:success] = "Updated #{num_overdue_tasks} task due" \
                      " #{'date'.pluralize(num_overdue_tasks)} to today"
    redirect_to tasks_path(page: params[:page])
  end

  def search
    @quote = random_quote
    @awwyiss_modal = random_awwyiss_modal

    if params[:search_terms]
      @search_results = current_user.tasks.search(params[:search_terms],
                                                  params[:tasks_filter],
                                                  params[:task_category_filter],
                                                  params[:sort_by]).paginate(
                                                    page: params[:page],
                                                    per_page: 20
                                                  )
    else
      @search_results = []
    end
  end

  private

  def task_params
    params.require(:task).permit(:summary, :task_category_id, :priority,
                                 :status, :due_at, :completed_at)
  end

  # Task operations can be done from either the current tasks view
  # (index), upcoming tasks view, or search view. This ensures we redirect
  # to the correct tasks view we originated from.
  def redirect_to_correct_tasks_tab
    case params[:tasks_view]
    when 'upcoming'
      redirect_to upcoming_tasks_path(category: params[:category],
                                      page: params[:page])
    when 'search'
      redirect_to search_tasks_path(search_terms: params[:search_terms],
                                    tasks_filter: params[:tasks_filter],
                                    task_category_filter:
                                      params[:task_category_filter])
    else
      redirect_to tasks_path(category: params[:category], page: params[:page])
    end
  end

  # This serves the same purpose as redirect_to_correct_tasks_tab above, but
  # is used when only rendering the view rather than redirecting to it.
  def render_correct_tasks_tab
    # Only explicitly set view to a known set of views, otherwise an attacker
    # could render any view by setting params[:tasks_view]
    case params[:tasks_view]
    when 'index'
      view = 'index'
    when 'upcoming'
      view = 'upcoming'
    when 'search'
      view = 'search'
    else
      view = 'index'
    end

    render(view)
  end

  def random_quote
    # Use pluck to only get the ids from the quotes table and not load
    # all of the entries into memory:
    quote_ids = current_user.quotes.pluck(:id)
    return nil if quote_ids.empty?

    # Use sample to return a random id from the array:
    current_user.quotes.find(quote_ids.sample)
  end

  # Returns a list of meme modal template names that can be shown.
  def meme_modal_list
    # Customize your memes by adding partial templates in app/views/tasks/ and
    # reference them here:
    %w[awwyiss_modal_bravocado
       awwyiss_modal_like_a_boss
       awwyiss_modal_nice_one]
  end

  # Return the name of a random awwyiss modal template
  def random_awwyiss_modal
    awwyiss_modal_templates = meme_modal_list

    awwyiss_modal_templates[rand(awwyiss_modal_templates.length)]
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
  # Return CSS classes for this task based on its priority and whether the task
  # is completed.
  def task_status_class(task)
    cssclass = ''
    cssclass += 'task-priority1 ' if task.priority == 1
    cssclass += 'task-priority2 ' if task.priority == 2
    cssclass += 'task-completed ' if task.status == 'COMPLETED'

    cssclass
  end

  # Return an options_for_select array with task sorting options
  def task_sort_options
    [['Due Date - Oldest First', 'due-date-asc'],
     ['Due Date - Newest First', 'due-date-desc'],
     ['Priority - Higest First', 'priority-asc'],
     ['Priority - Lowest First', 'priority-desc']]
  end
end

app/views/tasks/_awwyiss_modal_nice_one.html.erb
<div class="modal fade" id="awwyiss_modal" tabindex="-1" role="dialog" aria-labelledby="awwyiss_model_label" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">

      <div class="modal-header">
        <h5 class="modal-title" id="awwyiss_model_label">Nice One!</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>

      <div class="modal-body">
        <%= image_tag('nice_one.gif', class: 'awwyiss-img', title: 'Nice One!') %>
      </div>

      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>

    </div>
  </div>
</div>

app/views/tasks/_display_tasks_paginated.html.erb
    <% if task_list.empty? %>
      <% if params[:page] and params[:page].to_i > 1 %>
        <p class="italic">There are no <%= task_list_type %> tasks to display for this page - maybe try going back one page?</p>
      <% else %>
        <p class="italic">There are no <%= task_list_type %> tasks <%= "in this category " unless params[:category].nil? %>to display.</p>
      <% end %>
    <% else %>
      <div id="<%= task_list_type %>_task_list">
      <%= render partial: 'display_task', collection: task_list, as: :display_task %>
      <%= will_paginate task_list %>
      </div>
    <% end %>

app/views/tasks/_editable_task.html.erb
<div id="task_<%= editable_task.id %>_container">
  <div id="editable_task_<%= editable_task.id %>" class="row flex-wrap editable-task">
    <%= form_with model: editable_task, url: task_path(
          editable_task,
          category: params[:category],
          page: params[:page],
          search_terms: params[:search_terms],
          tasks_filter: params[:tasks_filter],
          task_category_filter: params[:task_category_filter]),
          class: 'form-inline', local: true do |f| %>

      <%= hidden_field_tag 'tasks_view', params[:tasks_view] %>

      <div class="editable-task-delete">
        <%= link_to image_tag('delete-icon.svg', class: "task-delete-icon"),
          task_path(editable_task, tasks_view: params[:tasks_view]), method: :delete,
          data: { confirm: 'Delete this task?' }, :class => 'action destroy' %>
      </div>

      <div class='editable-task-summary'>
        <%= f.text_field :summary, placeholder: "Summary",
          class: "form-control form-control-sm #{form_validity_class(editable_task, 'summary')}" %>
        <%= raw validation_error_html(editable_task, 'summary', 'Summary') %>
      </div>

      <div class='editable-task-task-category'>
        Category: <%= f.select :task_category_id, current_user.task_categories.map { |tc| [tc.name, tc.id] }, {},
          { class: "form-control form-control-sm #{form_validity_class(editable_task, 'task_category_id')}" } %>
        <%= raw validation_error_html(editable_task, 'task_category_id', 'Task Category') %>
      </div>

      <div class='editable-task-priority'>
        Priority: <%= f.select :priority, [1, 2, 3], {},
          { class: "form-control form-control-sm #{form_validity_class(editable_task, 'priority')}" } %>
        <%= raw validation_error_html(editable_task, 'priority', 'Priority') %>
      </div>

      <div class='editable-task-due-on'>
        Due on: <%= f.text_field :due_at,
          class: "form-control form-control-sm date-picker-input #{form_validity_class(editable_task, 'due_at')}", id: "editable_task_#{ editable_task.id }_date_picker" %>
        <%= raw validation_error_html(editable_task, 'due_at', 'Due Date') %>
      </div>

      <div class="editable-task-submit">
        <%= f.submit "Update Task", class: "btn btn-sm btn-primary update-task-btn" %>
      </div>

      <div class="editable-task-cancel">
        <span>or <%= link_to "Cancel", task_path(editable_task), remote: true %></span>
      </div>
    <% end %>
  </div>
</div>

app/views/tasks/_new_task_form.html.erb
<%= form_with model: new_task, url: tasks_path(
      category: params[:category],
      page: params[:page],
      search_terms: params[:search_terms],
      tasks_filter: params[:tasks_filter],
      task_category_filter: params[:task_category_filter]),
      local: true do |f| %>

  <%= hidden_field_tag 'tasks_view', tasks_view %>

  <div class="form-row">
    <div class="col-5">
      <%= f.text_field :summary, placeholder: "Summary",
        class: "form-control form-control-sm #{form_validity_class(new_task, 'summary')}" %>
      <%= raw validation_error_html(new_task, 'summary', 'Summary') %>
    </div>

    <div class="col-auto">
      Due at:
      <%= f.text_field :due_at,
        class: "form-control form-control-sm date-picker-input #{form_validity_class(new_task, 'due_at')}" %>
      <%= raw validation_error_html(new_task, 'due_at', 'Due Date') %>
    </div>

    <div class="col-auto">
      Category:
      <%= f.select :task_category_id, current_user.task_categories.map { |tc| [tc.name, tc.id] }, {},
        { class: "form-control form-control-sm select-inline #{form_validity_class(new_task, 'task_category_id')}" } %>
      <%= raw validation_error_html(new_task, 'task_category_id', 'Task Category') %>
    </div>

    <div class="col-auto">
      Priority:
      <%= f.select :priority, [1, 2, 3], {},
        { class: "form-control form-control-sm select-inline #{form_validity_class(new_task, 'priority')}" } %>
      <%= raw validation_error_html(new_task, 'priority', 'Priority') %>
    </div>
  </div>

  <div class="form-row">
    <div class="col-auto">
      <%= f.submit "Create Task", class: "btn btn-sm btn-primary create-task-btn" %>
    </div>
  </div>
<% end %>

app/views/tasks/_quote_container.html.erb
<% if current_user.setting.display_quotes? %>
  <div id="header_quote_container">
  <% if current_user.quotes.empty? %>
    <blockquote id="header_quotation">"To add custom quotes to appear here - or disable the display of quotes altogether - manage your quotes from the <%= link_to 'Settings menu', quotes_path %>."
      <footer id="header_quotation_source">-ProgressPuppy</footer>
    </blockquote>
  <% else %>
    <blockquote id="header_quotation">"<%= quote.quotation %>"
      <footer id="header_quotation_source">-<%= quote.source %></footer>
    </blockquote>
  <% end %>
  </div>
<% end %>

app/views/tasks/_task_category_filter_buttons.html.erb
<div id="task_category_filters" style="margin-bottom: 1.0rem">
  <% if params[:category].nil? %>
    <%= link_to "All Categories", {}, :class => 'badge badge-primary' %>
  <% else %>
    <%= link_to "All Categories", {}, :class => 'badge badge-secondary',
                'data-toggle': 'tooltip', 'data-placement': 'top',
                title: 'Show tasks in all categories' %>
  <% end %>
  <% current_user.task_categories.sort_by(&:name).each do |tc| %>
    <% if params[:category] == tc.name %>
      <%= link_to tc.name, { :category => tc.name },
                  :class => 'badge badge-primary' %>
    <% else %>
      <%= link_to tc.name, { :category => tc.name },
                  :class => 'badge badge-secondary',
                  'data-toggle': 'tooltip', 'data-placement': 'top',
                  title: "Show only #{tc.name} tasks" %>
    <% end %>
  <% end %>
</div>

app/views/tasks/_task_nav_tabs.html.erb
<ul id="task_nav_tabs" class="nav nav-tabs">
  <li class="nav-item">
    <%= link_to "Today's Tasks", tasks_path, class: "nav-link #{'active' if current_page?(tasks_path) or current_page?(root_path)}" %>
  </li>
  <li class="nav-item">
    <%= link_to "Upcoming Tasks", upcoming_tasks_path, class: "nav-link #{'active' if current_page?(upcoming_tasks_path)}" %>
  </li>
  <li class="nav-item">
    <%= link_to "Search", search_tasks_path, class: "nav-link #{'active' if current_page?(search_tasks_path)}" %>
  </li>

  <%= render 'layouts/flash_alerts_inline' %>
</ul>

app/views/tasks/_task_sort_selector.html.erb
<div class="task-sort-selector-container">
  <%= form_tag "", class: "form-inline" do %>
    <%= label_tag :sort_by, "Sort by:" %>
    <%= select_tag :sort_by, options_for_select(task_sort_options,
                                                params[:sort_by]),
      { onchange: "search_results_sort_by()",
        class: "form-control form-control-sm" } %>
  <% end %>
</div>

app/views/tasks/edit.js.erb
$('#task_<%= @task.id %>_container').replaceWith("<%= j render 'editable_task', editable_task: @task, current_user: @current_user %>")
$('#editable_task_<%= @task.id %>_date_picker').datepicker({ format: 'yyyy-mm-dd', autoclose: true, todayBtn: "linked", todayHighlight: true, clearBtn: true, daysOfWeekHighlighted: '06', zIndexOffset: 2000 })

app/views/tasks/index.html.erb
<div class="container">
  <div id="awwyiss_container">
    <%= render @awwyiss_modal %>
  </div>

  <%= render 'quote_container', quote: @quote %>

  <h2 class="task-header">
    New Task
    <%= link_to image_tag('chevron-down.svg',
                          id: 'toggle_new_task_form_control'),
                          "/", id: 'toggle_new_task_form_control_link',
                          'data-toggle': 'tooltip', 'data-placement': 'right',
                          title: "Click this arrow to show/hide the new task form" %>
  </h2>
  <hr />

  <div id="new_task_container" class="<%= new_task_form_display_class %>">
  <%= render 'new_task_form', new_task: @new_task, tasks_view: 'index', current_user: @current_user %>
  </div>

  <%= render 'task_nav_tabs' %>

  <div id="current_tasks_container">
    <div id="task_category_filters_container">
      <%= render 'task_category_filter_buttons', current_user: @current_user %>

      <% if @overdue_tasks > 0 %>
      <div id="advance_overdue_tasks_button_container">
        <%= button_to "Advance Overdue Tasks", advance_overdue_tasks_path(page: params[:page]),
          class: 'btn btn-sm btn-tiny btn-primary',
          'data-toggle': 'tooltip', 'data-placement': 'top',
          title: 'This button will update all tasks that are currently overdue to have a new due date of today' %>
      </div>
      <% end %>
    </div>

    <%= render 'display_tasks_paginated', task_list: @current_tasks,
                                          task_list_type: 'current' %>
  </div>

  <h2 class="task-header">Today's Completed Tasks</h2>
  <hr />

  <div id="completed_tasks_container">
    <div id="completed_task_list">
      <% if @completed_tasks.empty? %>
        <p class="italic">There are no completed tasks for today.<p>
      <% else %>
        <%= render partial: 'display_task', collection: @completed_tasks, as: :display_task %>
      <% end %>
    </div>
  </div>

</div>

app/views/tasks/search.html.erb
<div class="container">
  <div id="awwyiss_container">
    <%= render @awwyiss_modal %>
  </div>

  <%= render 'quote_container', quote: @quote %>

  <div id="new_task_placeholder"></div>

  <%= render 'task_nav_tabs' %>

  <div id="task_search_form">
    <%= form_tag search_tasks_path, method: :get do %>
      <div id="text_search" class="d-flex flex-row">
        <%= text_field_tag :search_terms, params[:search_terms], class: "no-margins form-control form-control-sm" %>
        <%= submit_tag 'Search Tasks', name: nil, class: "no-margins btn btn-sm btn-primary" %>
      </div>

      <div class="d-flex flex-row">
        <div class="form-check form-check-inline">
          <%= radio_button_tag 'tasks_filter', 'all', true, class: "form-check-input" %>
          <%= label_tag 'tasks_all', 'All Tasks', class: "form-check-label" %>
        </div>
        <div class="form-check form-check-inline">
          <%= radio_button_tag 'tasks_filter', 'completed', false, class: "form-check-input" %>
          <%= label_tag 'tasks_completed', 'Completed Tasks', class: "form-check-label" %>
        </div>
        <div class="form-check form-check-inline">
          <%= radio_button_tag 'tasks_filter', 'incomplete', false, class: "form-check-input" %>
          <%= label_tag 'tasks_incomplete', 'Incomplete Tasks', class: "form-check-label" %>
        </div>

        <div id="category_search" class="form-inline">
          <%= label_tag :task_category_filter, "in Category:", class: "form-label" %>
          <%= select_tag :task_category_filter, options_for_select(['All'] + @current_user.task_categories.map { |tc| [tc.name, tc.id] }), { class: "form-control form-control-sm" } %>
        </div>
      </div>
    <% end %>
  </div>

  <div id="search_results_header" class="flex-header">
    <h2 class="task-header">Search Results</h2>
    <% unless @search_results.empty? %>
      <%= render 'task_sort_selector' %>
    <% end%>
  </div>
  <hr />

  <div id="search_results_container">
    <div id="search_results_task_list">
      <% if @search_results.empty? %>
        <p class="italic">There are no search results to display.</p>
      <% else %>
        <%= render partial: 'display_task', collection: @search_results, as: :display_task %>
        <%= will_paginate @search_results %>
      <% end %>
    </div>
  </div>

</div>

app/views/tasks/show.js.erb
$('#task_<%= @task.id %>_container').replaceWith("<%= j render 'display_task', display_task: @task %>")

app/views/tasks/toggle_task_status.js.erb
<% if @task.status == "COMPLETED" %>
$('#awwyiss_container').html("<%= j render @awwyiss_modal %>")
$('#awwyiss_modal').modal('show')
$('#current_task_list').html("<%= j render partial: 'display_task', collection: @current_tasks, as: :display_task %>")
$('#completed_task_list').html("<%= j render partial: 'display_task', collection: @completed_tasks, as: :display_task %>")
<% else %>
$('#completed_task_list').html("<%= j render partial: 'display_task', collection: @completed_tasks, as: :display_task %>")
$('#current_task_list').html("<%= j render partial: 'display_task', collection: @current_tasks, as: :display_task %>")
<% end %>

app/views/tasks/upcoming.html.erb
<div class="container">
  <div id="awwyiss_container">
    <%= render @awwyiss_modal %>
  </div>

  <%= render 'quote_container', quote: @quote %>

  <h2 class="task-header">
    New Task
    <%= link_to image_tag('chevron-down.svg',
      id: 'toggle_new_task_form_control', title: 'Show/hide the new task form') %>
  </h2>
  <hr />

  <div id="new_task_container" class="<%= new_task_form_display_class %>">
  <%= render 'new_task_form', new_task: @new_task, tasks_view: 'upcoming', current_user: @current_user %>
  </div>

  <%= render 'task_nav_tabs' %>

  <div id="future_tasks_container">
    <div id="task_category_filters_container">
      <%= render 'task_category_filter_buttons', current_user: @current_user %>
    </div>

    <%= render 'display_tasks_paginated', task_list: @future_tasks,
                                          task_list_type: 'upcoming' %>
  </div>

</div>