config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root   'tasks#index'

  get    '/terms_of_service', to: 'pages#terms_of_service'

  get    '/signup', to: 'users#new'
  post   '/signup', to: 'users#create'
  get    '/thanks', to: 'users#thanks'
  get    '/user_profile', to: 'users#edit'

  get    '/resend_activation', to: 'account_activations#resend'
  get    '/password_resets/confirmation', to: 'password_resets#sent', as: :password_reset_sent

  get    '/login',  to: 'sessions#new'
  post   '/login',  to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get    'settings/edit'
  post   'settings/toggle_display_quotes'

  get    'task_categories/delete_confirmation/:id', to: 'task_categories#delete_confirmation', as: :task_category_delete_with_confirmation

  get    'tasks/upcoming', to: 'tasks#upcoming', as: :upcoming_tasks
  get    'tasks/search', to: 'tasks#search', as: :search_tasks
  post   'task/toggle_task_status/:id', to: 'tasks#toggle_task_status', as: :toggle_task_status
  post   'task/advance_overdue_tasks', to: 'tasks#advance_overdue_tasks', as: :advance_overdue_tasks

  resources :users,               except: [:index, :show, :edit]
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :tasks
  resources :task_categories,     except: [:new]
  resources :quotes,              except: [:new]
end

app/models/user.rb
class User < ApplicationRecord
  has_one :setting, dependent: :destroy
  has_many :task_categories, dependent: :destroy
  has_many :tasks, dependent: :destroy
  has_many :quotes, dependent: :destroy

  attr_accessor :accepted_tos, :activation_token, :reset_token, :remember_token

  has_secure_password

  # Validation
  EMAIL_REGEX = /\A[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,4}\Z/i.freeze

  validates :first_name, presence: true,
                         length: { maximum: 50 }

  validates :last_name, presence: true,
                        length: { maximum: 50 }

  validates :email, presence: true,
                    length: { within: 3..255 },
                    format: EMAIL_REGEX,
                    uniqueness: { case_sensitive: false },
                    confirmation: true

  validates :password, presence: true, length: { minimum: 10 }, allow_nil: true
  validates :accepted_tos, acceptance: true

  # Make it easier to prevent email duplicates by downcasing them by default:
  before_save   :downcase_email
  before_create :create_activation_digest
  after_create  :create_user_settings, :create_default_task_category

  # Returns the hash digest of the given string
  def self.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # Returns a random token
  def self.new_token
    SecureRandom.urlsafe_base64
  end

  # Remembers a user in the database for use in persistent sessions
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # Returns true if the given token matches the digest
  def authenticated?(attribute, token)
    # self is implied with send here:
    digest = send("#{attribute}_digest")
    return false if digest.nil?

    BCrypt::Password.new(digest).is_password?(token)
  end

  # Forgets a user
  def forget
    update_attribute(:remember_digest, nil)
  end

  # Activates an account
  def activate
    update(activated: true, activated_at: Time.zone.now)
  end

  # Sends activation email
  def send_activation_email
    UserMailer.account_activation(self).deliver_now
    # Log the ToS acceptance time
    self.accepted_tos_at = Time.zone.now
    save
  end

  # Re-sends activation email with a new link
  def resend_activation_email
    create_activation_digest
    save
    UserMailer.account_activation(self).deliver_now
  end

  # Sets the password reset attributes
  def create_reset_digest
    self.reset_token = User.new_token
    update(reset_digest: User.digest(reset_token), reset_sent_at: Time.zone.now)
  end

  # Sends password reset email
  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end

  # Returns true if a password reset has expired
  def password_reset_expired?
    reset_sent_at < 2.hours.ago
  end

  private

  # Returns email in all lowercase
  def downcase_email
    email.downcase!
  end

  # Creates and assigns the activation token and digest
  def create_activation_digest
    self.activation_token = User.new_token
    self.activation_digest = User.digest(activation_token)
  end

  # Ensure each User has an associated Setting object
  def create_user_settings
    self.setting = Setting.new
  end

  # Ensure each User has an 'Uncategorized' TaskCategory that will be used for
  # tasks where a TaskCategory is not set
  def create_default_task_category
    task_categories << TaskCategory.new(name: 'Uncategorized')
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: %i[edit update destroy]
  before_action :correct_user,   only: %i[update]
  before_action :admin_user,     only: :destroy

  def new
    # Logged-in users get redirected to the root_url
    redirect_to root_path if current_user.present?
    @user = User.new
  end

  def create
    # Logged-in users get redirected to their profile page
    redirect_to user_profile_path if current_user.present?
    @user = User.new(user_params)
    if @user.save
      @user.send_activation_email
      redirect_to thanks_path
    else
      render 'new'
    end
  end

  def edit
    @user = current_user
  end

  def update
    @user = User.find_by_id(params[:id])
    if @user.nil?
      flash[:danger] = 'Update failed: User not found'
      redirect_to(root_path)
    end

    if @user.update(user_params)
      flash[:success] = 'Profile updated'
      redirect_to user_profile_path
    else
      render 'edit'
    end
  end

  def destroy
    user = User.find_by_id(params[:id])
    if user.nil?
      flash[:danger] = 'Deleting User failed: user not found'
      redirect_to(root_path)
    end

    user.destroy
    flash[:success] = 'User deleted'
    redirect_to users_url
  end

  # Static page with user instructions to activate account
  def thanks
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password,
                                 :password_confirmation, :time_zone,
                                 :accepted_tos)
  end

  # Before filters

  # Confirms the correct user.
  def correct_user
    @user = User.find_by_id(params[:id])
    redirect_to(root_url) unless current_user?(@user)
  end

  # Confirms an admin user.
  def admin_user
    redirect_to(root_url) unless current_user.admin?
  end
end

app/views/users/_form.html.erb
<%= form_with model: user, local: true do |f| %>
  <%= f.label :first_name, "First Name:" %>
  <%= f.text_field :first_name,
    class: "form-control #{form_validity_class(user, 'first_name')}" %>
  <%= raw validation_error_html(user, 'first_name', 'First name') %>

  <%= f.label :last_name, "Last Name:" %>
  <%= f.text_field :last_name,
    class: "form-control #{form_validity_class(user, 'last_name')}" %>
  <%= raw validation_error_html(user, 'last_name', 'Last name') %>

  <%= f.label :email, "Email:" %>
  <%= f.email_field :email,
    class: "form-control #{form_validity_class(user, 'email')}" %>
  <%= raw validation_error_html(user, 'email', 'Email') %>

  <%= f.label :password, "Password:" %>
  <%= f.password_field :password,
    class: "form-control #{form_validity_class(user, 'password')}" %>
  <%= raw validation_error_html(user, 'password', 'Password') %>

  <%= f.label :password_confirmation, "Confirm Password:" %>
  <%= f.password_field :password_confirmation,
    class: "form-control #{form_validity_class(user, 'password')}" %>
  <%= raw validation_error_html(user, 'password_confirmation', 'Password confirmation') %>

  <%= f.label :time_zone, "Time Zone:" %>
  <%= f.time_zone_select :time_zone, nil,
    { include_blank: false },
    { class: "form-control #{form_validity_class(user, 'time_zone')}" } %>
  <%= raw validation_error_html(user, 'time_zone', 'Time zone') %>

  <%= f.submit "Save Changes", class: "btn btn-primary" %>
<% end %>

app/views/users/edit.html.erb
<% provide(:button_text, 'Save Changes') %>
<h1>User Profile</h1>

<div id="edit_user_profile_alerts_container" class="mx-auto">
  <%= render 'layouts/flash_alerts_static' %>
</div>

<div id="edit_user_profile_form_container" class="container">
  <div class="mx-auto">
    <%= render 'form', user: @user %>
  </div>
</div>

app/views/users/new.html.erb
<h1>Sign Up for Free</h1>

<% if params[:landing_page] %>
<div class="alert-container">
  <div id="landing_page_referral_alert" class="alert alert-success">
    <p>If you already have a ProgressPuppy account, <%= link_to "log in", login_path %> and access your Subscription Plan Settings page to upgrade your account to a paid plan.</p>

    <p>But if you don't have a ProgressPuppy account yet, we encourage you to sign up for free below and try out our free plan first to make sure ProgressPuppy meets your needs. We're not sending you to a credit card form just yet, because <strong>we want to make sure you enjoy using ProgressPuppy first</strong>! You can then always upgrade your plan from your Subscription Plan Settings page.</p>
  </div>
</div>
<% end %>

<div class="container">
  <div class="col-md-6 col-md-offset-3 mx-auto">

    <%= form_with model: @user, :url => signup_path, local: true do |f| %>
      <%= f.label :first_name, "First Name:" %>
      <%= f.text_field :first_name, placeholder: "First Name",
        class: "form-control #{form_validity_class(@user, 'first_name')}" %>
      <%= raw validation_error_html(@user, 'first_name', 'First name') %>

      <%= f.label :last_name, "Last Name:" %>
      <%= f.text_field :last_name, placeholder: "Last Name",
        class: "form-control #{form_validity_class(@user, 'last_name')}" %>
      <%= raw validation_error_html(@user, 'last_name', 'Last name') %>

      <%= f.label :email, "Email Address:" %>
      <%= f.email_field :email, placeholder: "Email",
        class: "form-control #{form_validity_class(@user, 'email')}" %>
      <%= raw validation_error_html(@user, 'email', 'Email') %>

      <%= f.label :password, "Password (at least 10 characters):" %>
      <%= f.password_field :password, placeholder: "Password",
        class: "form-control #{form_validity_class(@user, 'password')}" %>
      <%= raw validation_error_html(@user, 'password', 'Password') %>

      <%= f.label :password_confirmation, "Confirm Password:" %>
      <%= f.password_field :password_confirmation, placeholder: "Confirm password",
        class: "form-control #{form_validity_class(@user, 'password')}" %>
      <%= raw validation_error_html(@user, 'password_confirmation', 'Password confirmation') %>

      <%= f.label :time_zone, "Time Zone:" %>
      <%= f.time_zone_select :time_zone, nil,
        { include_blank: false, default: "Pacific Time (US & Canada)" },
        { class: "form-control #{form_validity_class(@user, 'time_zone')}" } %>
      <%= raw validation_error_html(@user, 'time_zone', 'Time zone') %>

      <div class="form-group form-check">
        <%= f.check_box :accepted_tos, class: "form-check-input new-user-checkbox" %>
        <%= f.label :accepted_tos, "I have read and agree to the ProgressPuppy <a href='/terms_of_service' target='_blank' rel='noopener noreferrer'>Terms of Service</a>, <a href='https://www.iubenda.com/privacy-policy/77152679' target='_blank' rel='noopener noreferrer'>Privacy Policy</a>, and <a href='https://www.iubenda.com/privacy-policy/77152679/cookie-policy' target='_blank' rel='noopener noreferrer'>Cookie Policy</a>.".html_safe, class: "form-check-label" %>
        <%= raw validation_error_html(@user, 'accepted_tos', 'The Terms of Service, Privacy Policy, and Cookie Policy') %>
      </div>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>

  </div>
</div>

app/views/users/thanks.html.erb
<h1>Signup Confirmation</h1>

Thanks for creating an account! We have just sent you an email with a link to activate your account. Please click this link to verify your email address, and welcome to ProgressPuppy!