config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root   'tasks#index'

  get    '/terms_of_service', to: 'pages#terms_of_service'

  get    '/signup', to: 'users#new'
  post   '/signup', to: 'users#create'
  get    '/thanks', to: 'users#thanks'
  get    '/user_profile', to: 'users#edit'

  get    '/resend_activation', to: 'account_activations#resend'
  get    '/password_resets/confirmation', to: 'password_resets#sent', as: :password_reset_sent

  get    '/login',  to: 'sessions#new'
  post   '/login',  to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get    'settings/edit'
  post   'settings/toggle_display_quotes'

  get    'task_categories/delete_confirmation/:id', to: 'task_categories#delete_confirmation', as: :task_category_delete_with_confirmation

  get    'tasks/upcoming', to: 'tasks#upcoming', as: :upcoming_tasks
  get    'tasks/search', to: 'tasks#search', as: :search_tasks
  post   'task/toggle_task_status/:id', to: 'tasks#toggle_task_status', as: :toggle_task_status
  post   'task/advance_overdue_tasks', to: 'tasks#advance_overdue_tasks', as: :advance_overdue_tasks

  resources :users,               except: [:index, :show, :edit]
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :tasks
  resources :task_categories,     except: [:new]
  resources :quotes,              except: [:new]
end

app/views/layouts/_alerts.html.erb
<div class="alert-container">
</div>

app/views/layouts/_alerts_inline.html.erb
<div class="alert-flex-container">
  <%= content_tag :div, message.html_safe,
      class: "alert alert-#{message_type} alert-compact hide-by-default",
      data: { "fade-on-demand": true } %>
</div>

app/views/layouts/_flash_alerts.html.erb
<div class="alert-container">
  <% flash.each do |message_type, message| %>
    <%= content_tag :div, message.html_safe,
      class: "alert alert-#{message_type}",
      data: { "fade-out": true } %>
  <% end %>
</div>

app/views/layouts/_flash_alerts_inline.html.erb
<div class="alert-flex-container">
  <% flash.each do |message_type, message| %>
    <%= content_tag :div, message.html_safe,
      class: "alert alert-#{message_type} alert-compact",
      data: { "fade-out": true } %>
  <% end %>
</div>

app/views/layouts/_flash_alerts_static.html.erb
<div class="alert-container">
  <% flash.each do |message_type, message| %>
    <%= content_tag :div, message.html_safe,
      class: "alert alert-#{message_type}" %>
  <% end %>
</div>

app/views/layouts/_flash_alerts_static_wide.html.erb
<div class="alert-container-wide">
  <% flash.each do |message_type, message| %>
    <%= content_tag :div, message.html_safe,
      class: "alert alert-#{message_type}" %>
  <% end %>
</div>

app/views/layouts/_footer.html.erb
<footer id="page_footer">
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-sm navbar-dark bg-dark fixed-top">
  <div class="container">
    <%= link_to "ProgressPuppy FOSS", smart_root_path, id: "logo", class: "navbar-brand" %>
    <% if logged_in? %>
      <div class="dropdown show">
        <a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Settings
        </a>
        <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
          <%= link_to "User Profile", user_profile_path, class: "dropdown-item" %>
          <%= link_to "Task Categories", task_categories_path, class: "dropdown-item" %>
          <%= link_to "Quotes", quotes_path, class: "dropdown-item" %>
          <%= link_to "Log out", logout_path, method: :delete, class: "dropdown-item" %>
        </div>
      </div>
    <% else %>
      <ul class="navbar-nav">
        <li class="nav-item"><%= link_to "Log in", login_path, class: "nav-link" %></li>
      </ul>
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>ProgressPuppy - FOSS Edition</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">

      <%= yield %>

      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>